### ISSUE TITLE
People automatically paired on Out of Office board

### ISSUE THREAD

**Issue by taavo** [Pinwheeler/Parrit#11]
If I put someone on the Out of Office board, and then hit Recommend Pairs, Parrit will pair people with the people who aren't in the office. It'd be great if Parrit would treat my OOO people as though they were ineligible for pairing.

Or am I just doing it wrong?

**Comment by Pinwheeler** [comment]
You are not doing anything wrong- the functionality just isn't built into Parrit yet. I'm currently putting together a CLI for Parrit, but I'll break from that and see how easy this task is.

**Comment by taavo** [comment]
Thanks! Our team is really excited about Parrit, and this is one of the features that would make using it over Pairtrix or a big whiteboard an easier decision.

**Comment by Pinwheeler** [comment]
Hey @taavo, just wanted to give you an update on this. I'm basically feature complete, just need a way to give every project an 'exempt' board. Ideally this would be some kind of migration and I'm still pretty unskilled at SQL- I expect to have this feature launched by the end of the week if my struggles prove successful

**Comment by Pinwheeler** [comment]
Feature merged b9ef926fcd9bfafb4309df950a73526511ac5879
