### ISSUE TITLE
Adding people broken on parrit.cfapps.io

### ISSUE THREAD

**Issue by geoffwa** [Pinwheeler/Parrit#12]
We're getting a 500 when trying to add a person to the team:

```json
{
"timestamp":1472132333048,
"status":500,"error":"Internal Server Error",
"exception":"org.springframework.dao.DataIntegrityViolationException",
"message":"could not execute statement; SQL [n/a]; constraint [person_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
"path":"/api/project/226/addPerson"
}
```

**Comment by Pinwheeler** [comment]
This was the sequence getting out of sync with the actual index of people. I may or may not have done some data recovery work last night :|

It should be working now, I'll do the same fix on the other tables. Thanks for bringing up the issue!
