### ISSUE TITLE
Recommend Pairs returns 500 on Safari

### ISSUE THREAD

**Issue by geoffwa** [Pinwheeler/Parrit#13]
It looks like we make a request for `application/json`, but we're getting a `text/html` response.

I'm not good with the Safari webtools but I can see:
```html
<script>
   runError();
</script>
```
in the response body.

😢

**Comment by Pinwheeler** [comment]
@geoffwa hey geoff, sorry about the bugs on Parrot this morning, I pushed a new feature last night and being the deployment newb that I am must have bungled some stuff. I'll work on them tonight and see if we can't get back to normal by tomorrow morning

**Comment by Pinwheeler** [comment]
@geoffwa I'm unable to reproduce this now that I made the changes raised in #12. Is this still happening for you? And if so, what's the name of your project? I'll make a copy of the data and play around with it.

**Comment by geoffwa** [comment]
Will check it tomorrow - might have been fixed, we're project recon (#226 I
think)

**Comment by professorviz** [comment]
We're still seeing this issue on Chrome in Boulder

**Comment by zachgersh** [comment]
hey @Pinwheeler - I also saw this on when attempting to try this out for release engineering. Can show you tomorrow when you are in the office. This is Chrome as well.

**Comment by Pinwheeler** [comment]
I copied over @geoffwa's project info and reproduced the error. Latest commit/push should have resolved it
