### ISSUE TITLE
Some people's names are longer than 10 characters

### ISSUE THREAD

**Issue by genevievelesperance** [Pinwheeler/Parrit#21]
Trying to add a Parrit teammate and the error is "Hey! This name is too long... 10 characters max."

**Comment by rosenhouse** [comment]
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by Pinwheeler** [comment]
Increased name character limit to 100, let me know if I need to go into the database to change your new teammate's name

**Comment by rosenhouse** [comment]
Awesome, thanks Anthony!
