### ISSUE TITLE
Reset pairs

### ISSUE THREAD

**Issue by lurraca** [Pinwheeler/Parrit#22]
We used Parrit in our last project and we think it's a good idea and would like to contribute to it.

One thing that bothered us was having to drag every person label out, and then assign back in and hit "recommend pairs". We were thinking of having a button to "Reset board/pairs" to give the pairing a clean slate when needed instead of having to manually drag each pair out of their boards.

Is this something that makes sense to you guys? We could create a tracker story for it and work on it.

**Comment by sylvialai** [comment]
Glad to hear your team used it! We heard similar feedback about being able to easily automate the assigned pairs back to floating.  

We created a tracker story https://www.pivotaltracker.com/story/show/132044999 in the backlog, and we are currently working on the design, will attach the Zeplin link once we have the design ready.

**Comment by ashwell** [comment]
Fullstack LA in SM here! Picking this one up!

**Comment by ashwell** [comment]
PR #39 Submitted!
