### ISSUE TITLE
Cannot create project or log in

### ISSUE THREAD

**Issue by lennyk** [Pinwheeler/Parrit#5]
Front end client receives `500 Internal Server Error`. Provides inconsistent error messages in the UI (sometimes not at all), but details can be seen with dev tools.

**Create Project Example**

```
Request URL:http://parrit.cfapps.io/api/project/new
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:52.0.145.236:80
```

**Login Example**

```
Request URL:http://parrit.cfapps.io/login/project
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:52.0.145.236:80
```

**Comment by Pinwheeler** [comment]
Hey Leonhard,

Turns out this was a database concurrent connections issue on our day 1 release. Nice problem to have, eh? Anyway, should be working now.
